name: Decrypt ChaCha20 File

on:
  workflow_dispatch:

jobs:
  decrypt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install cryptography

      - name: Jalankan dekripsi
        run: python3 decrypt.py
