name: Encrypt ChaCha20 File

on:
  workflow_dispatch:

jobs:
  encrypt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install cryptography

      - name: Jalankan enkripsi
        run: python3 encrypt.py

      - name: Upload hasil enkripsi ke folder result
        uses: actions/upload-artifact@v4
        with:
          name: encrypted-result
          path: result/
      - name: Commit dan push hasil ke repositori
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git add result/
          git status
          git diff --cached --quiet || git commit -m "Add encrypted result files" || echo "❗ Tidak ada perubahan untuk di-commit"
          git push
