name: Encrypt ChaCha20 File

on:
  workflow_dispatch:

jobs:
  encrypt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install cryptography

      - name: Jalankan enkripsi
        run: python3 encrypt.py

      - name: Upload hasil enkripsi
        uses: actions/upload-artifact@v4
        with:
          name: encrypted-result
          path: locked/
